# **Practical 3A**

CLASSFICATION USING DNN

In [ ]:
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense


dataset=loadtxt("/content/sample_data/pima-indians-diabetes.csv",delimiter=',');
dataset

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [ ]:
X=dataset[:,0:8]
Y=dataset[:,8]

In [ ]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [ ]:
Y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [ ]:
#Creating model
model=Sequential()
model.add(Dense(12,input_dim=8,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

#Compiling and fitting model
model.compile(loss="binary_crossentropy",optimizer='adam',metrics=['accuracy'])
model.fit(X,Y,epochs=150,batch_size=10)

Epoch 1/150
77/77 [==============================] - 1s 1ms/step - loss: 5.2630 - accuracy: 0.3997
Epoch 2/150
77/77 [==============================] - 0s 919us/step - loss: 1.3363 - accuracy: 0.5143
Epoch 3/150
77/77 [==============================] - 0s 1ms/step - loss: 0.8956 - accuracy: 0.5898
Epoch 4/150
77/77 [==============================] - 0s 962us/step - loss: 0.7757 - accuracy: 0.6211
Epoch 5/150
77/77 [==============================] - 0s 975us/step - loss: 0.7109 - accuracy: 0.6380
Epoch 6/150
77/77 [==============================] - 0s 1ms/step - loss: 0.6851 - accuracy: 0.6484
Epoch 7/150
77/77 [==============================] - 0s 986us/step - loss: 0.6646 - accuracy: 0.6484
Epoch 8/150
77/77 [==============================] - 0s 1ms/step - loss: 0.6632 - accuracy: 0.6419
Epoch 9/150
77/77 [==============================] - 0s 979us/step - loss: 0.6517 - accuracy: 0.6628
Epoch 10/150
77/77 [==============================] - 0s 904us/step - loss: 0.6429 - accuracy: 0.66

In [ ]:
model.fit(X,Y,epochs=150,batch_size=10)
predictions=model.predict(X)
rounded=[round(x[0])for x in predictions]
print(rounded)
scores=model.evaluate(X,Y)
print("\n%s: %.2f%%"%(model.metrics_names[1],scores[1]*100))

Epoch 1/150
77/77 [==============================] - 0s 979us/step - loss: 0.4995 - accuracy: 0.7474
Epoch 2/150
77/77 [==============================] - 0s 993us/step - loss: 0.4931 - accuracy: 0.7500
Epoch 3/150
77/77 [==============================] - 0s 906us/step - loss: 0.5020 - accuracy: 0.7487
Epoch 4/150
77/77 [==============================] - 0s 934us/step - loss: 0.4991 - accuracy: 0.7526
Epoch 5/150
77/77 [==============================] - 0s 942us/step - loss: 0.4948 - accuracy: 0.7565
Epoch 6/150
77/77 [==============================] - 0s 943us/step - loss: 0.5018 - accuracy: 0.7630
Epoch 7/150
77/77 [==============================] - 0s 1ms/step - loss: 0.4990 - accuracy: 0.7604
Epoch 8/150
77/77 [==============================] - 0s 1ms/step - loss: 0.4917 - accuracy: 0.7643
Epoch 9/150
77/77 [==============================] - 0s 1ms/step - loss: 0.4904 - accuracy: 0.7617
Epoch 10/150
77/77 [==============================] - 0s 933us/step - loss: 0.4960 - accuracy: 0.

# **Practical 3B**
**BINARY CLASSIFICATION USING MLP**


In [ ]:
# mlp for binary classification
from pandas import read_csv
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
# load the dataset
path = '/content/sample_data/ionosphere.csv'
df = read_csv(path, header=None)
# split into input and output columns
X, y = df.values[:, :-1], df.values[:, -1]
# ensure all data are floating point values
X = X.astype('float32')
# encode strings to integer
y = LabelEncoder().fit_transform(y)
# split into train and test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)
# determine the number of input features
n_features = X_train.shape[1]
# define model
model = Sequential()
model.add(Dense(10, activation='relu', kernel_initializer='he_normal', input_shape=(n_features,)))
model.add(Dense(8, activation='relu', kernel_initializer='he_normal'))
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# fit the model
model.fit(X_train, y_train, epochs=150, batch_size=32, verbose=0)
# evaluate the model
loss, acc = model.evaluate(X_test, y_test, verbose=0)
print('Test Accuracy: %.3f' % acc)
# make a prediction
row = [1,0,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1,0.03760,0.85243,-0.17755,0.59755,-0.44945,0.60536,-0.38223,0.84356,-0.38542,0.58212,-0.32192,0.56971,-0.29674,0.36946,-0.47357,0.56811,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300]
yhat = model.predict([row])
print('Predicted: %.3f' % yhat)


(235, 34) (116, 34) (235,) (116,)
Test Accuracy: 0.940
Predicted: 0.984
